 
#All contacts (Suceess✅)
GET http://localhost:3000/contacts
Content-Type: application/json

#View contact by ID (Suceess✅)
GET http://localhost:3000/contacts/681f82594cbd2c4b5392f7e2
Content-Type: application/json

#Create a new contact (Suceess✅)
POST http://localhost:3000/contacts 
Content-Type: application/json

{
    "firstName": "Maria",
    "lastName": "Borges",
    "email": "mborges@createnew.com",
    "favoriteColor": "blue",
    "birthday": "1965-05-07"
}

#Update a contact (Suceess✅)
PUT http://localhost:3000/contacts/681f82594cbd2c4b5392f7e2
Content-Type: application/json

{
    "firstName": "Mayara",
    "lastName": "Alves",
    "email": "mayara@updatecontact.com",
    "favoriteColor": "green",
    "birthday": "1999-08-03"
 }

#Delete a contact(Suceess✅)
DELETE http://localhost:3000/contacts/681f82594cbd2c4b5392f7e2
Content-Type: application/json

#Create a new contact 2 (Suceess✅)
POST http://localhost:3000/contacts 
Content-Type: application/json

{
    "firstName": "Mayara",
    "lastName": "Alves",
    "email": "mayara@updatecontact.com",
    "favoriteColor": "green",
    "birthday": "1999-08-03"
 }